import asyncio
import json
from decimal import Decimal
from unittest.mock import patch, MagicMock

from backend.app.schemas import ArtisanFacts
from backend.app.services.ai_adapter import generate_catalog_draft

def test_1_telugu_artisan_facts_generation():
    """Test 1 — Telugu: ArtisanFacts in Telugu receives canonical JSON, maps native fields, preserves English, no AI pricing."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Wooden Toy Statue",
                        "description": "Handcrafted wooden doll painted with natural dyes.",
                        "craft_story": "Handcrafted over 2 days in Kondapalli style.",
                        "materials": ["Wood", "Natural Dyes"],
                        "category": "Wooden Toys",
                        "tags": ["Wood", "Toy"],
                        "native_title": "హ్యాండ్‌క్రాఫ్టెడ్ చెక్క బొమ్మ",
                        "native_description": "సహజ రంగులతో అమర్చిన సాంప్రదాయ చెక్క బొమ్మ.",
                        "native_craft_story": "రెండు రోజులలో శ్రద్ధగా తయారు చేసిన హస్తకళ."
                    })
                }]
            }
        }]
    }

    facts = ArtisanFacts(
        product_name="చెక్క బొమ్మ",
        craft_type="Wooden Toys",
        materials=["చెక్క", "సహజ రంగులు"],
        handmade=True,
        making_time="రెండు రోజులు",
        artisan_story="",
        special_characteristics=""
    )

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response) as mock_post:
        draft = asyncio.run(generate_catalog_draft(
            artisan_facts=facts,
            language="te"
        ))

        # 1. Verify prompt contains canonical ArtisanFacts JSON
        call_kwargs = mock_post.call_args[1]
        sent_prompt = call_kwargs["json"]["contents"][0]["parts"][0]["text"]
        assert "CANONICAL SOURCE OF TRUTH (ARTISAN FACTS):" in sent_prompt
        assert '"product_name": "చెక్క బొమ్మ"' in sent_prompt

        # 2. Native fields map to Telugu
        assert draft["title"] == "హ్యాండ్‌క్రాఫ్టెడ్ చెక్క బొమ్మ"
        assert draft["description"] == "సహజ రంగులతో అమర్చిన సాంప్రదాయ చెక్క బొమ్మ."
        assert draft["craft_story"] == "రెండు రోజులలో శ్రద్ధగా తయారు చేసిన హస్తకళ."

        # 3. English fields remain English
        assert draft["title_en"] == "Wooden Toy Statue"
        assert draft["description_en"] == "Handcrafted wooden doll painted with natural dyes."
        assert draft["craft_story_en"] == "Handcrafted over 2 days in Kondapalli style."

        # 4. No pricing generated by Gemini
        assert draft["pricing_available"] is False
        assert draft["pricing_source"] == "AWAITING_ARTISAN_INPUT"


def test_2_missing_materials_handling():
    """Test 2 — Missing Materials: When materials in ArtisanFacts is [], materials remains empty/Not specified."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Handmade Decorative Bowl",
                        "description": "Artisan handmade bowl created with care.",
                        "craft_story": "Handcrafted over one full day.",
                        "materials": [],
                        "category": "Handcrafted",
                        "tags": ["Handmade", "Bowl"],
                        "native_title": "Handmade Decorative Bowl",
                        "native_description": "Artisan handmade bowl created with care.",
                        "native_craft_story": "Handcrafted over one full day."
                    })
                }]
            }
        }]
    }

    facts = ArtisanFacts(
        product_name="Handmade Bowl",
        craft_type="Handcrafted",
        materials=[],
        handmade=None,
        making_time="one day",
        artisan_story="",
        special_characteristics=""
    )

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            artisan_facts=facts,
            language="en"
        ))

        assert draft["materials"] == "" or draft["materials"] == []
        assert "ceramic" not in draft["materials"].lower()
        assert "clay" not in draft["materials"].lower()
        assert "wood" not in draft["materials"].lower()
        assert "metal" not in draft["materials"].lower()


def test_3_no_heritage_hallucination():
    """Test 3 — No Heritage: When artisan_story is empty, output does NOT claim generations, ancestral, or GI status."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Artisan Craft Piece",
                        "description": "Simple handmade craft item.",
                        "craft_story": "Handmade craft piece crafted directly by the artisan.",
                        "materials": ["Wood"],
                        "category": "Handcrafted",
                        "tags": ["Craft", "Handmade"],
                        "native_title": "Artisan Craft Piece",
                        "native_description": "Simple handmade craft item.",
                        "native_craft_story": "Handmade craft piece crafted directly by the artisan."
                    })
                }]
            }
        }]
    }

    facts = ArtisanFacts(
        product_name="Craft Item",
        artisan_story=""
    )

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            artisan_facts=facts,
            language="en"
        ))

        story = draft["craft_story"].lower()
        assert "three generations" not in story
        assert "ancestral" not in story
        assert "centuries-old" not in story
        assert "gi certification" not in story
        assert "awards" not in story


def test_4_explicit_facts_only_sanitization():
    """Test 4 — Explicit Facts Only: Gemini attempting materials=['wood', 'teak', 'lacquer'] is sanitized to facts materials."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Wooden Toy",
                        "description": "Handmade wooden toy.",
                        "craft_story": "Handcrafted wooden item.",
                        "materials": ["wood", "teak", "lacquer"],
                        "category": "Wooden Toys",
                        "tags": ["Wood", "Toy"],
                        "native_title": "Wooden Toy",
                        "native_description": "Handmade wooden toy.",
                        "native_craft_story": "Handcrafted wooden item."
                    })
                }]
            }
        }]
    }

    facts = ArtisanFacts(
        product_name="Wooden Toy",
        materials=["wood"]
    )

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            artisan_facts=facts,
            language="en"
        ))

        # Application sanitizer filters out unmentioned 'lacquer'
        assert "lacquer" not in draft["materials"].lower()
        assert "wood" in draft["materials"].lower()


def test_5_backward_compatibility_qna_answers():
    """Test 5 — Backward Compatibility: generate_catalog_draft with qna_answers produces valid response."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Handloom Sari",
                        "description": "Pure cotton handwoven sari.",
                        "craft_story": "Handwoven over 3 days.",
                        "materials": ["Cotton"],
                        "category": "Handloom",
                        "tags": ["Cotton", "Sari"],
                        "native_title": "Handloom Sari",
                        "native_description": "Pure cotton handwoven sari.",
                        "native_craft_story": "Handwoven over 3 days."
                    })
                }]
            }
        }]
    }

    qna = {
        "q1_title": "Cotton Sari",
        "q2_materials": "Cotton",
        "q3_story": "3 days weaving"
    }

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            qna_answers=qna,
            language="en"
        ))

        assert draft["source"] == "LIVE_AI"
        assert draft["title"] == "Handloom Sari"
        assert draft["materials"] == "Cotton"


def test_6_legacy_voice_description_compatibility():
    """Test 6 — Legacy voice_description: Calling generate_catalog_draft with voice_description does not crash."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Handmade Clay Pot",
                        "description": "Clay pot crafted by hand.",
                        "craft_story": "Clay pot crafted by hand.",
                        "materials": [],
                        "category": "Terracotta",
                        "tags": ["Clay", "Pot"],
                        "native_title": "Handmade Clay Pot",
                        "native_description": "Clay pot crafted by hand.",
                        "native_craft_story": "Clay pot crafted by hand."
                    })
                }]
            }
        }]
    }

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            voice_description="Handmade clay pot crafted by hand",
            language="en"
        ))

        assert draft["title"] == "Handmade Clay Pot"
        assert draft["source"] == "LIVE_AI"


def test_7_cost_plus_pricing_calculation():
    """Test 7 — Pricing Engine: Costs specified return protected 20% floor & cost-plus margin without altering pricing behavior."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Handmade Craft",
                        "description": "Artisan product description.",
                        "craft_story": "Artisan product story.",
                        "materials": ["Wood"],
                        "category": "Handcrafted",
                        "tags": ["Handmade"],
                        "native_title": "Handmade Craft",
                        "native_description": "Artisan product description.",
                        "native_craft_story": "Artisan product story."
                    })
                }]
            }
        }]
    }

    facts = ArtisanFacts(product_name="Handmade Craft", materials=["Wood"])

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            artisan_facts=facts,
            material_cost=Decimal("600.00"),
            labour_cost=Decimal("500.00"),
            packaging_cost=Decimal("100.00"),
            other_cost=Decimal("0.00"),
            language="en"
        ))

        assert draft["material_cost"] == Decimal("600.00")
        assert draft["labour_cost"] == Decimal("500.00")
        assert draft["packaging_cost"] == Decimal("100.00")
        assert draft["other_cost"] == Decimal("0.00")
        assert draft["min_fair_price"] == Decimal("1440.00")
        assert draft["suggested_price"] == Decimal("1680.00")
        assert draft["pricing_source"] == "COST_PLUS_MARGIN"
        assert draft["pricing_available"] is True


def test_8_native_mapping_verification():
    """Test 8 — Native Mapping: language='te' maps title -> native_title and title_en -> English title."""
    mock_gemini_response = MagicMock()
    mock_gemini_response.status_code = 200
    mock_gemini_response.json.return_value = {
        "candidates": [{
            "content": {
                "parts": [{
                    "text": json.dumps({
                        "title": "Kondapalli Wooden Toy",
                        "description": "Traditional wooden toy from Andhra Pradesh.",
                        "craft_story": "Crafted over 2 days by traditional artisans.",
                        "materials": ["Wood"],
                        "category": "Wooden Toys",
                        "tags": ["Wood", "Toy"],
                        "native_title": "కొండపల్లి బొమ్మ",
                        "native_description": "ఆంధ్రప్రదేశ్ సాంప్రదాయ చెక్క బొమ్మ.",
                        "native_craft_story": "రెండు రోజులలో శ్రద్ధగా తయారు చేసిన హస్తకళ."
                    })
                }]
            }
        }]
    }

    facts = ArtisanFacts(product_name="కొండపల్లి బొమ్మ", materials=["Wood"])

    with patch("backend.app.services.ai_adapter.GEMINI_API_KEY", "mock-key"), \
         patch("httpx.AsyncClient.post", return_value=mock_gemini_response):
        draft = asyncio.run(generate_catalog_draft(
            artisan_facts=facts,
            language="te"
        ))

        assert draft["title"] == "కొండపల్లి బొమ్మ"
        assert draft["description"] == "ఆంధ్రప్రదేశ్ సాంప్రదాయ చెక్క బొమ్మ."
        assert draft["craft_story"] == "రెండు రోజులలో శ్రద్ధగా తయారు చేసిన హస్తకళ."
        assert draft["title_en"] == "Kondapalli Wooden Toy"
        assert draft["description_en"] == "Traditional wooden toy from Andhra Pradesh."
        assert draft["craft_story_en"] == "Crafted over 2 days by traditional artisans."


def test_9_manual_draft_fallback_preserves_artisan_facts():
    """Test 9 — Manual Fallback: When force_fallback=True or AI fails, ArtisanFacts are preserved in manual draft."""
    facts = ArtisanFacts(
        product_name="Kondapalli Wooden Toy",
        craft_type="Wooden Toys",
        materials=["wood", "natural dyes"],
        artisan_story="2 days crafting time"
    )

    draft = asyncio.run(generate_catalog_draft(
        artisan_facts=facts,
        language="en",
        force_fallback=True
    ))

    assert draft["source"] == "MANUAL_DRAFT"
    assert draft["title"] == "Kondapalli Wooden Toy"
    assert draft["category"] == "Wooden Toys"
    assert draft["materials"] == "wood, natural dyes"
    assert draft["craft_story"] == "2 days crafting time"

