import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext();

export const CATEGORY_TRANSLATIONS = {
  'All Crafts': {
    te: 'అన్ని కళారూపాలు',
    hi: 'सभी हस्तशिल्प',
    en: 'All Crafts',
    ta: 'அனைத்து கைவினைப்பொருட்கள்',
    bn: 'সমস্ত কারুশিল্প'
  },
  'Kalamkari': {
    te: 'కలంకారి',
    hi: 'कलमकारी',
    en: 'Kalamkari',
    ta: 'கலம்காரி',
    bn: 'কলমকারী'
  },
  'Wooden Toys': {
    te: 'చెక్క బొమ్మలు',
    hi: 'लकड़ी के खिलौने',
    en: 'Wooden Toys',
    ta: 'மர பொம்மைகள்',
    bn: 'কাঠের খেলনা'
  },
  'Blue Pottery': {
    te: 'బ్లూ పాట్టరీ',
    hi: 'ब्लू पॉटरी',
    en: 'Blue Pottery',
    ta: 'ப்ளூ பாட்டரி',
    bn: 'ব্লু পটারি'
  },
  'Bidriware': {
    te: 'బిద్రివేర్',
    hi: 'बीदरीवेयर',
    en: 'Bidriware',
    ta: 'பித்ரிவேர்',
    bn: 'বিদ্রিওয়্যার'
  },
  'Pochampally Ikat': {
    te: 'పోచంపల్లి ఇకత్',
    hi: 'पोचमपल्ली इकत',
    en: 'Pochampally Ikat',
    ta: 'போச்சம்பள்ளி இகத்',
    bn: 'পোচমপল্লী ইকত'
  },
  'Terracotta': {
    te: 'టెర్రకోట',
    hi: 'टेराकोटा',
    en: 'Terracotta',
    ta: 'டெரகோட்டா',
    bn: 'টেরাকোটা'
  },
  'Handloom': {
    te: 'చేనేత (హ్యాండ్‌లూమ్)',
    hi: 'हथकरघा (हैंडलूम)',
    en: 'Handloom',
    ta: 'கைத்தறி',
    bn: 'তাঁত (হ্যান্ডলুম)'
  }
};

export const TRANSLATIONS = {
  te: {
    selectLanguageTitle: 'మీ ప్రాధాన్య భాషను ఎంచుకోండి',
    selectLanguageSub: 'Artisan AI మీ మాతృభాషలో స్పష్టమైన గైడెన్స్ మరియు సమాచారాన్ని అందిస్తుంది.',
    continueBtn: 'కొనసాగించండి',
    navbarTitle: 'చేతివృత్తుల AI మార్కెట్‌ప్లేస్',
    addProductBtn: '🎨 + ప్రొడక్ట్ జోడించండి (AI Guide)',
    buyerCopilotBtn: '🤖 AI బయ్యర్ గైడ్',
    sellTab: 'కళాకారుల డాష్‌బోర్డ్',
    buyTab: 'మార్కెట్‌ప్లేస్ వర్గం',
    analyticsTab: 'సేల్స్ & బిజినెస్ రిపోర్ట్',
    heroTag: 'కళాకారుల రక్షిత ధర & డిజిటల్ కామర్స్',
    minFairPriceLabel: '20% ప్రొటెక్టెడ్ మినిమమ్ లాభం ధర',
    smartPricingLabel: 'ఆటో స్మార్ట్ ప్రైసింగ్ స్విచ్',
    publishBtn: 'మార్కెట్‌లో నేరుగా Publish చేయండి',
    editAiDraftBtn: 'సవరించండి (Edit AI Draft)',
    photoStepTitle: '1. ఫోటోలు అప్‌లోడ్ చేయండి',
    photoStepSub: 'మీ ప్రొడక్ట్ ఫోటోలు యాడ్ చేయండి, ఆపై Next నొక్కండి',
    nameStepTitle: '2. ఉత్పత్తి పేరు & వివరాలు',
    costStepTitle: '3. శ్రమ & మెటీరియల్ ఖర్చులు',
    storyStepTitle: '4. ప్రొడక్ట్ ప్రత్యేకత / వాయిస్ స్టోరీ',
    reviewStepTitle: '5. AI డ్రాఫ్ట్ పరిశీలన & 20% రక్షిత ధర',
    searchPlaceholder: 'కళాఖండాలు లేదా చేతివృత్తులను వెతకండి...',
    allCrafts: 'అన్ని కళారూపాలు',
    directFairPrice: 'రక్షిత న్యాయమైన ధర',
    buyNow: 'ఇప్పుడే కొనండి',
    preOrder: 'ముందస్తు ఆర్డర్',
    viewDetails: 'వివరాలు చూడండి',
    yourCraft: 'మీ ఉత్పత్తి',
    outOfStock: 'అందుబాటులో లేదు',
    inStock: 'అందుబాటులో ఉంది',
    craftPassport: '🧾 క్రాఫ్ట్ పాస్‌పోర్ట్',
    handmade: 'చేతితో చేసినది',
    productionTime: 'తయారీ సమయం',
    rawMaterials: 'ముడి సరుకులు',
    craftDescription: 'ఉత్పత్తి వివరాలు',
    craftStory: 'వారసత్వ కథ',
    translateBtn: '🌐 AI అనువాదం',
    translating: 'అనువదిస్తోంది...',
    meetArtisan: 'కళాకారుడిని కలవండి',
    viewProfile: 'ప్రొఫైల్ చూడండి',
    saveToWishlist: 'కోరికల జాబితాలో చేర్చండి',
    home: 'హోమ్',
    artisanStudio: 'కళాకారుల స్టూడియో',
    buyerMarketplace: 'లైవ్ మార్కెట్‌ప్లేస్',
    signIn: 'లాగిన్',
    enterpriseTag: 'ఎంటర్‌ప్రైజ్',
    offline: 'ఆఫ్‌లైన్',
    cloud: 'క్లౌడ్',
    studio: 'స్టూడియో',
    market: 'మార్కెట్',
    filters: 'ఫిల్టర్లు',
    rankedByInterest: 'కొనుగోలుదారుల ఆసక్తి ప్రకారం ర్యాంక్ చేయబడింది',
    buyerMarketplaceBanner: 'లైవ్ మార్కెట్‌ప్లేస్ (విక్రయదారులకు ప్రత్యక్ష కనెక్షన్)',
    directHeritageTitle: 'సాంప్రదాయ కళాకారుల నుండి నేరుగా వారసత్వ కళారూపాలు',
    directHeritageSub: 'మధ్యవర్తులను తొలగించండి. ప్రతి వీక్షణ, సేవ్ మరియు ఆర్డర్ గ్రామీణ కళాకారులకు న్యాయమైన ధరను అందిస్తాయి.',
    searchPlaceholderMarketplace: 'కలంకారీ, చెక్క బొమ్మలు, మెటీరియల్స్ వెతకండి...',
    trendingHeritageCrafts: 'ట్రెండింగ్ వారసత్వ కళారూపాలు',
    highDemand: 'అత్యధిక డిమాండ్',
    allArtisanCollections: 'అన్ని కళాకారుల సేకరణలు',
    craftsAvailable: 'ఉత్పత్తులు అందుబాటులో ఉన్నాయి',
    resetFilters: 'ఫిల్టర్లను రీసెట్ చేయండి',
    aiCopilotGuidanceBtn: '🤖 AI బయ్యర్ అసిస్టెంట్',
    dashboard: 'డాష్‌బోర్డ్',
    myProducts: 'నా ఉత్పత్తులు',
    smartPricing: 'స్మార్ట్ ప్రైసింగ్ & లాభం',
    ordersAndFulfillment: 'ఆర్డర్లు & డెలివరీ',
    marketIntelligence: 'మార్కెట్ డిమాండ్',
    salesChannels: 'సేల్స్ ఛానెళ్లు (ONDC)',
    aiAssistantHeader: '🤖 చేతివృత్తుల AI అసిస్టెంట్',
    askMeAnything: 'నన్ను ఏమైనా అడగండి (ఉదా: 20% లాభం ఎలా లెక్కించబడుతుంది?)...',
    generateAiDraftBtn: '🪄 AI కేటలాగ్ డ్రాఫ్ట్ సృష్టించండి',
    nextBtn: 'తరువాత (Next)',
    backBtn: 'వెనుకకు (Back)',
    recordVoiceStory: '🎙️ మీ స్వరంలో కథను చెప్పండి (రకార్డు చేయండి)',
    ondcPlatformTag: 'భారతీయ హస్తకళల డిజిటల్ వేదిక • ONDC Ready Platform',
    heroHeadlineText: 'వాయిస్ AI & న్యాయమైన వాణిజ్యంతో భారతీయ కళాకారులకు సాధికారత.',
    heroSubheadText: 'మధ్యవర్తుల దోపిడీని అంతం చేస్తూ, బహుభాషా వాయిస్ AI, ఖర్చు-ప్లస్ 20% లాభ రక్షణ ధర మరియు ప్రత్యక్ష కొనుగోలుదారుల అనుసంధానం.',
    enterStudio: 'కళాకారుల స్టూడియోలో ప్రవేశించండి',
    artisanSignInJoin: 'కళాకారుల సైన్ ఇన్ / చేరండి',
    exploreMarketplace: 'మార్కెట్‌ప్లేస్‌ను పరిశీలించండి (హస్తకళలు కొనండి)',
    trustDirectArtisan: '100% నేరుగా కళాకారుడికి',
    trust5Languages: '5 భారతీయ భాషలు',
    trustMarginGuard: '≥ 20% లాభ రక్షణ',
    trustNoMiddlemen: 'మధ్యవర్తుల కమీషన్లు సున్నా',
    whyTrustTitle: 'గ్రామీణ కళాకారులు మరియు కొనుగోలుదారులు Artisan AI ని ఎందుకు విశ్వసిస్తారు',
    whyTrustSub: 'భారతదేశమంతటా చేతివృత్తులవారు ఎదుర్కొంటున్న సమస్యలను పరిష్కరించడానికి రూపొందించబడింది.',
    preservingHeritageTag: 'భారతీయ సాంస్కృతిక వారసత్వ రక్షణ',
    giCraftsTitle: 'ప్రామాణిక GI గుర్తింపు పొందిన భారతీయ కళారూపాలు',
    viewAllCraftsMarketplace: 'మార్కెట్‌ప్లేస్‌లో అన్ని కళాఖండాలను చూడండి',
    exploreInCatalog: 'కేటలాగ్‌లో పరిశీలించండి',
    howItWorksTitle: 'ఇది ఎలా పనిచేస్తుంది',
    howItWorksSub: 'గ్రామీణ కళాకారుడికి సరళమైన పద్ధతి. కొనుగోలుదారుడికి నమ్మకం మరియు స్పష్టత.',
    forMasterArtisans: 'ప్రధాన కళాకారుల కోసం (Master Artisans)',
    fromWorkshopToGlobal: 'వర్క్‌షాప్ నుండి ప్రపంచ విపణికి నిమిషాల్లో',
    artisanStep1Text: 'మాట్లాడండి & ఫోటో తీయండి: మీ మాతృభాషలో మాట్లాడి ఫోటోను అప్‌లోడ్ చేయండి.',
    artisanStep2Text: 'తక్షణ న్యాయమైన ధర: AI కనీస 20% లాభంతో రక్షిత ధరను లెక్కిస్తుంది.',
    artisanStep3Text: 'ప్రత్యక్ష కొనుగోలుదారులు: కమీషన్లు లేకుండా నేరుగా వాట్సాప్ కాల్స్ మరియు ఆర్డర్లు పొందండి.',
    forConsciousBuyers: 'కొనుగోలుదారుల కోసం (Conscious Buyers)',
    directProvenance: 'నేరుగా కళాకారుడి నుండి, సున్నా మధ్యవర్తి మార్కప్‌లు',
    buyerStep1Text: 'ప్రామాణిక కళలను చూడండి: GI ట్యాగ్ మరియు కళాకారుల వివరాల ప్రకారం వెతకండి.',
    buyerStep2Text: 'ధర పారదర్శకత: ముడి సరుకులు, శ్రమ మరియు కళాకారుడి సంపాదన వివరాలు చూడండి.',
    buyerStep3Text: 'నేరుగా ఆర్డర్ చేయండి: వాట్సాప్ ద్వారా నేరుగా ఆర్డర్లు మరియు హోల్‌సేల్ విచారణలు చేయండి.',
    readyToExperience: 'భారతీయ హస్తకళల డిజిటల్ విపణిని అనుభవించడానికి సిద్ధంగా ఉన్నారా?',
    joinThousands: 'వేలాది గ్రామీణ కళాకారుల చేతివృత్తులను నేరుగా మీ ఇంటికి చేర్చండి.',
    startAsArtisan: 'కళాకారుడిగా ప్రారంభించండి',
    shopHandmadeCrafts: 'చేతివృత్తులను కొనండి',
    connectingBackend: 'Artisan AI సర్వర్‌కి కనెక్ట్ అవుతోంది...',
    homeShowcase: 'హోమ్ ప్రదర్శన',
    offlineLocalCache: 'ఆఫ్‌లైన్ (లోకల్ కేష్)',
    liveCloudDb: 'లైవ్ (క్లౌడ్ DB)',
    nativeOnboardingBadge: 'మాతృభాషా ఎంపిక',
    selectLanguageModalTitle: 'మీ భాషను ఎంచుకోండి',
    selectLanguageModalSub: 'Artisan AI మీ మాతృభాషలో స్పష్టమైన గైడెన్స్ మరియు సేవలను అందిస్తుంది.',
    workspaceLabel: 'వర్క్‌స్పేస్',
    syncLabel: 'సింక్',
    databaseLabel: 'డేటాబేస్',
    connectedStatus: 'కనెక్ట్ అయింది'
  },
  hi: {
    selectLanguageTitle: 'अपनी पसंदीदा भाषा चुनें',
    selectLanguageSub: 'Artisan AI आपकी मातृभाषा में मार्गदर्शन और जानकारी प्रदान करता है।',
    continueBtn: 'आगे बढ़ें',
    navbarTitle: 'कारीगर AI मार्केटप्लेस',
    addProductBtn: '🎨 + नया उत्पाद जोड़ें (AI Guide)',
    buyerCopilotBtn: '🤖 AI क्रेता गाइड',
    sellTab: 'कारीगर डैशबोर्ड',
    buyTab: 'बाज़ार वर्ग',
    analyticsTab: 'बिक्री रिपोर्ट',
    heroTag: 'सुरक्षित न्यूनतम लाभ और डिजिटल व्यापार',
    minFairPriceLabel: '20% सुरक्षित न्यूनतम लाभ मूल्य',
    smartPricingLabel: 'ऑटो स्मार्ट मूल्य निर्धारण',
    publishBtn: 'बाज़ार में लाइव प्रकाशित करें',
    editAiDraftBtn: 'संपादित करें (Edit AI Draft)',
    photoStepTitle: '1. तस्वीरें अपलोड करें',
    photoStepSub: 'अपने उत्पाद की तस्वीरें जोड़ें, फिर Next दबाएं',
    nameStepTitle: '2. उत्पाद नाम और विवरण',
    costStepTitle: '3. श्रम और सामग्री लागत',
    storyStepTitle: '4. हस्तशिल्प कहानी / आवाज संदेश',
    reviewStepTitle: '5. AI ड्राफ्ट समीक्षा और 20% सुरक्षित मूल्य',
    searchPlaceholder: 'हस्तशिल्प या कारीगरी खोजें...',
    allCrafts: 'सभी हस्तशिल्प',
    directFairPrice: 'सुरक्षित उचित मूल्य',
    buyNow: 'अभी खरीदें',
    preOrder: 'प्री-ऑर्डर करें',
    viewDetails: 'विवरण देखें',
    yourCraft: 'आपका उत्पाद',
    outOfStock: 'स्टॉक में नहीं',
    inStock: 'स्टॉक में उपलब्ध',
    craftPassport: '🧾 क्राफ्ट पासपोर्ट',
    handmade: 'हस्तनिर्मित',
    productionTime: 'निर्माण समय',
    rawMaterials: 'कच्ची सामग्री',
    craftDescription: 'उत्पाद विवरण',
    craftStory: 'विरासत कहानी',
    translateBtn: '🌐 AI अनुवाद',
    translating: 'अनुवाद हो रहा है...',
    meetArtisan: 'कारीगर से मिलें',
    viewProfile: 'प्रोफ़ाइल देखें',
    saveToWishlist: 'इच्छासूची में सहेजें',
    home: 'होम',
    artisanStudio: 'कारीगर स्टूडियो',
    buyerMarketplace: 'लाइव मार्केटप्लेस',
    signIn: 'साइन इन',
    enterpriseTag: 'एंटरप्राइज',
    offline: 'ऑफ़लाइन',
    cloud: 'क्लाउड',
    studio: 'स्टूडियो',
    market: 'बाज़ार',
    filters: 'फ़िल्टर',
    rankedByInterest: 'क्रेता रुचि के अनुसार रैंक किया गया',
    buyerMarketplaceBanner: 'लाइव मार्केटप्लेस (कारीगरों से सीधा संबंध)',
    directHeritageTitle: 'पारंपरिक कारीगरों से सीधे हस्तशिल्प',
    directHeritageSub: 'बिचौलियों को हटाएं। हर व्यू, सेव और ऑर्डर ग्रामीण कारीगरों को उचित मूल्य प्रदान करता है।',
    searchPlaceholderMarketplace: 'कलमकारी, लकड़ी के खिलौने, सामग्री खोजें...',
    trendingHeritageCrafts: 'ट्रेंडिंग हस्तशिल्प',
    highDemand: 'उच्च मांग',
    allArtisanCollections: 'सभी कारीगर संग्रह',
    craftsAvailable: 'उत्पाद उपलब्ध हैं',
    resetFilters: 'फ़िल्टर रीसेट करें',
    aiCopilotGuidanceBtn: '🤖 AI क्रेता सहायक',
    dashboard: 'डैशबोर्ड',
    myProducts: 'मेरे उत्पाद',
    smartPricing: 'स्मार्ट मूल्य निर्धारण और लाभ',
    ordersAndFulfillment: 'ऑर्डर और डिलीवरी',
    marketIntelligence: 'बाज़ार की मांग',
    salesChannels: 'बिक्री चैनल (ONDC)',
    aiAssistantHeader: '🤖 कारीगर AI सहायक',
    askMeAnything: 'मुझसे कुछ भी पूछें (उदा: 20% लाभ कैसे सुरक्षित होता है?)...',
    generateAiDraftBtn: '🪄 AI कैटलॉग ड्राफ्ट बनाएं',
    nextBtn: 'आगे बढ़ें (Next)',
    backBtn: 'पीछे जाएं (Back)',
    recordVoiceStory: '🎙️ अपनी आवाज में कहानी बताएं (रिकॉर्ड करें)',
    ondcPlatformTag: 'भारतीय हस्तशिल्प डिजिटल मंच • ONDC Ready Platform',
    heroHeadlineText: 'वॉइस AI और निष्पक्ष व्यापार के साथ भारतीय कारीगरों को सशक्त बनाना।',
    heroSubheadText: 'बिचौलियों के शोषण को समाप्त करते हुए, बहुभाषी वॉइस AI, लागत-प्लस 20% लाभ सुरक्षा मूल्य और प्रत्यक्ष खरीदार संबंध।',
    enterStudio: 'कारीगर स्टूडियो में प्रवेश करें',
    artisanSignInJoin: 'कारीगर साइन इन / शामिल हों',
    exploreMarketplace: 'मार्केटप्लेस देखें (हस्तशिल्प खरीदें)',
    trustDirectArtisan: '100% सीधे कारीगर को',
    trust5Languages: '5 भारतीय भाषाएं',
    trustMarginGuard: '≥ 20% लाभ सुरक्षा',
    trustNoMiddlemen: 'शून्य बिचौलिए',
    whyTrustTitle: 'ग्रामीण कारीगर और खरीदार Artisan AI पर भरोसा क्यों करते हैं',
    whyTrustSub: 'भारत भर के शिल्पकारों द्वारा सामना की जाने वाली वास्तविक समस्याओं को हल करने के लिए निर्मित।',
    preservingHeritageTag: 'भारतीय विरासत का संरक्षण',
    giCraftsTitle: 'प्रमाणिक भौगोलिक संकेत (GI) हस्तशिल्प',
    viewAllCraftsMarketplace: 'मार्केटप्लेस में सभी हस्तशिल्प देखें',
    exploreInCatalog: 'कैटलॉग में देखें',
    howItWorksTitle: 'यह कैसे काम करता है',
    howItWorksSub: 'ग्रामीण कारीगर के लिए सरलता। खरीदार के लिए विश्वास और पारदर्शिता।',
    forMasterArtisans: 'मास्टर कारीगरों के लिए (Master Artisans)',
    fromWorkshopToGlobal: 'वर्कशॉप से वैश्विक बाज़ार तक मिनटों में',
    artisanStep1Text: 'बोलें और फोटो लें: अपनी मातृभाषा में बोलें और उत्पाद की फोटो जोड़ें।',
    artisanStep2Text: 'तत्काल उचित मूल्य: AI न्यूनतम 20% लाभ के साथ सुरक्षित मूल्य की गणना करता है।',
    artisanStep3Text: 'प्रत्यक्ष खरीदार: बिना किसी कमीशन के सीधे व्हाट्सएप कॉल और ऑर्डर प्राप्त करें।',
    forConsciousBuyers: 'जागरूक खरीदारों के लिए (Conscious Buyers)',
    directProvenance: 'सीधे कारीगर से, शून्य बिचौलिया मुनाफा',
    buyerStep1Text: 'प्रमाणिक हस्तशिल्प खोजें: GI टैग और कारीगर विवरण के अनुसार फ़िल्टर करें।',
    buyerStep2Text: 'मूल्य पारदर्शिता: कच्ची सामग्री, श्रम और कारीगर की कमाई का विवरण देखें।',
    buyerStep3Text: 'सीधे ऑर्डर करें: व्हाट्सएप के माध्यम से सीधे ऑर्डर और थोक पूछताछ करें।',
    readyToExperience: 'भारतीय हस्तशिल्प व्यापार का अनुभव करने के लिए तैयार हैं?',
    joinThousands: 'हजारों ग्रामीण कारीगरों के हस्तशिल्प को सीधे अपने घर लाएं।',
    startAsArtisan: 'कारीगर के रूप में शुरू करें',
    shopHandmadeCrafts: 'हस्तशिल्प खरीदें',
    connectingBackend: 'Artisan AI सर्वर से जुड़ रहा है...',
    homeShowcase: 'होम शोकेस',
    offlineLocalCache: 'ऑफ़लाइन (लोकल कैश)',
    liveCloudDb: 'लाइव (क्लाउड DB)',
    nativeOnboardingBadge: 'मातृभाषा चयन',
    selectLanguageModalTitle: 'अपनी भाषा चुनें',
    selectLanguageModalSub: 'Artisan AI आपकी मातृभाषा में मार्गदर्शन और सेवाएं प्रदान करता है।',
    workspaceLabel: 'वर्कस्पेस',
    syncLabel: 'सिंक',
    databaseLabel: 'डेटाबेस',
    connectedStatus: 'कनेक्टेड'
  },
  en: {
    selectLanguageTitle: 'Select Your Preferred Language',
    selectLanguageSub: 'Artisan AI provides step-by-step guidance and tools in your native language.',
    continueBtn: 'Continue',
    navbarTitle: 'Artisan AI Marketplace',
    addProductBtn: '🎨 + Add Craft Product (AI Guide)',
    buyerCopilotBtn: '🤖 AI Buyer Copilot',
    sellTab: 'Artisan Dashboard',
    buyTab: 'Live Marketplace',
    analyticsTab: 'Sales & Analytics',
    heroTag: 'Protected Fair Pricing & Digital Commerce',
    minFairPriceLabel: '20% Minimum Protected Profit Price',
    smartPricingLabel: 'Auto Smart Pricing Switch',
    publishBtn: 'Publish Live to Marketplace',
    editAiDraftBtn: 'Review & Edit AI Draft',
    photoStepTitle: '1. Upload Product Photos',
    photoStepSub: 'Add your product photos, then click Next',
    nameStepTitle: '2. Product Name & Details',
    costStepTitle: '3. Material & Labour Costs',
    storyStepTitle: '4. Craft Narrative / Voice Story',
    reviewStepTitle: '5. AI Draft Review & 20% Protected Price',
    searchPlaceholder: 'Search authentic artisan crafts...',
    allCrafts: 'All Crafts',
    directFairPrice: 'Direct Fair Price',
    buyNow: 'Buy Now',
    preOrder: 'Pre-Order',
    viewDetails: 'View Details',
    yourCraft: 'Your Craft',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    craftPassport: '🧾 Craft Passport',
    handmade: 'Handmade',
    productionTime: 'Production Time',
    rawMaterials: 'Raw Materials',
    craftDescription: 'Craft Description',
    craftStory: 'Heritage Craft Story',
    translateBtn: '🌐 AI Translate',
    translating: 'Translating...',
    meetArtisan: 'Meet the Artisan',
    viewProfile: 'View Profile',
    saveToWishlist: 'Save to Wishlist',
    home: 'Home',
    artisanStudio: 'Artisan Studio',
    buyerMarketplace: 'Live Marketplace',
    signIn: 'Sign In',
    enterpriseTag: 'Enterprise',
    offline: 'Offline',
    cloud: 'Cloud',
    studio: 'Studio',
    market: 'Market',
    filters: 'Filters',
    rankedByInterest: 'Ranked by buyer interest velocity',
    dashboard: 'Dashboard',
    myProducts: 'My Products',
    smartPricing: 'Smart Pricing & Profit',
    ordersAndFulfillment: 'Orders & Fulfillment',
    marketIntelligence: 'Market Intelligence',
    salesChannels: 'Sales Channels (ONDC)',
    aiAssistantHeader: '🤖 Artisan AI Voice Assistant',
    askMeAnything: 'Ask me anything in your language (e.g. How is 20% profit calculated?)...',
    generateAiDraftBtn: '🪄 Generate AI Catalog Draft',
    nextBtn: 'Next Step',
    backBtn: 'Back',
    recordVoiceStory: '🎙️ Record Voice Story in Your Language',
    ondcPlatformTag: 'Indian Digital Craft Platform • ONDC Ready Platform',
    heroHeadlineText: 'Empowering Indian Artisans with Voice-First AI & Fair Trade.',
    heroSubheadText: 'Eliminating predatory middlemen through Multilingual Voice AI, explainable cost-plus pricing protection, and direct buyer-to-artisan connections.',
    enterStudio: 'Enter Artisan Studio',
    artisanSignInJoin: 'Artisan Sign In / Join',
    exploreMarketplace: 'Explore Marketplace',
    trustDirectArtisan: '100% Direct to Artisan',
    trust5Languages: '5 Indian Languages',
    trustMarginGuard: '≥ 20% Profit Guard',
    trustNoMiddlemen: 'Zero Middleman Cuts',
    whyTrustTitle: 'Why Rural Creators & Discerning Buyers Trust Artisan AI',
    whyTrustSub: 'Built specifically to address the unique real-world barriers faced by craftspeople across India.',
    preservingHeritageTag: 'Preserving Indian Heritage',
    giCraftsTitle: 'Authentic Geographical Indication (GI) Crafts',
    viewAllCraftsMarketplace: 'View all crafts in Marketplace',
    exploreInCatalog: 'Explore in Catalog',
    howItWorksTitle: 'How It Works',
    howItWorksSub: 'Simplicity for the rural artisan. Confidence and transparency for the conscious buyer.',
    forMasterArtisans: 'For Master Artisans',
    fromWorkshopToGlobal: 'From workshop to global reach in minutes',
    artisanStep1Text: 'Speak & Snap: Take a photo of your craft and speak about materials & hours in your native mother tongue.',
    artisanStep2Text: 'Instant Fair Pricing: The AI calculates guaranteed profit floor (minimum 20% margin) and festival multipliers.',
    artisanStep3Text: 'Direct Buyer Enquiries: Receive WhatsApp calls and bulk order requests directly without commissions.',
    forConsciousBuyers: 'For Conscious Buyers',
    directProvenance: 'Direct provenance, zero middleman markups',
    buyerStep1Text: 'Browse Authentic Heritage: Filter by craft origin, GI tag status, and master artisan certifications.',
    buyerStep2Text: 'Fair Price Transparency: See the cost breakdown of raw materials, labor, and artisan earnings.',
    buyerStep3Text: 'Connect & Order Direct: Place orders or negotiate wholesale custom commissions directly via WhatsApp.',
    readyToExperience: 'Ready to experience authentic Indian artisan commerce?',
    joinThousands: 'Join thousands of rural artisans bringing timeless cultural crafts directly into homes worldwide.',
    startAsArtisan: 'Start as Artisan',
    shopHandmadeCrafts: 'Shop Handmade Crafts',
    connectingBackend: 'Connecting to Artisan AI backend...',
    homeShowcase: 'Home Showcase',
    offlineLocalCache: 'Offline (Local Cache)',
    liveCloudDb: 'Live (Cloud DB)',
    nativeOnboardingBadge: 'Native Language Onboarding',
    selectLanguageModalTitle: 'Select Your Language',
    selectLanguageModalSub: 'Artisan AI provides step-by-step guidance in your preferred native language.',
    workspaceLabel: 'Workspace',
    syncLabel: 'Sync',
    databaseLabel: 'Database',
    connectedStatus: 'Connected'
  },
  ta: {
    selectLanguageTitle: 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    selectLanguageSub: 'Artisan AI உங்கள் தாய்மொழியில் வழிகாட்டுதலை வழங்குகிறது.',
    continueBtn: 'தொடரவும்',
    navbarTitle: 'கைவினைஞர் AI சந்தை',
    addProductBtn: '🎨 + கைவினைப்பொருள் சேர் (AI Guide)',
    buyerCopilotBtn: '🤖 AI வாங்குபவர் வழிகாட்டி',
    sellTab: 'கைவினைஞர் டாஷ்போர்டு',
    buyTab: 'நேரலை சந்தை',
    analyticsTab: 'விற்பனை அறிக்கை',
    heroTag: 'பாதுகாக்கப்பட்ட நியாயமான விலை & டிஜிட்டல் வணிகம்',
    minFairPriceLabel: '20% குறைந்தபட்ச பாதுகாக்கப்பட்ட லாப விலை',
    smartPricingLabel: 'தானியங்கி ஸ்மார்ட் விலை அமைப்பு',
    publishBtn: 'சந்தையில் நேரடியாக வெளியிடவும்',
    editAiDraftBtn: 'AI வரைவை திருத்துங்கள்',
    photoStepTitle: '1. புகைப்படங்களை பதிவேற்றவும்',
    photoStepSub: 'உங்கள் புகைப்படங்களைச் சேர்த்து, Next என்பதைக் கிளிக் செய்யவும்',
    nameStepTitle: '2. தயாரிப்பு பெயர் & விவரங்கள்',
    costStepTitle: '3. பொருள் மற்றும் உழைப்பு செலவுகள்',
    storyStepTitle: '4. கைவினை கதை / குரல் பதிவு',
    reviewStepTitle: '5. AI வரைவு மதிப்பாய்வு & 20% பாதுகாக்கப்பட்ட விலை',
    searchPlaceholder: 'கைவினைப்பொருட்களைத் தேடுங்கள்...',
    allCrafts: 'அனைத்து கைவினைப்பொருட்கள்',
    directFairPrice: 'நியாயமான விலை',
    buyNow: 'இப்போதே வாங்குங்கள்',
    preOrder: 'முன்பதிவு செய்யுங்கள்',
    viewDetails: 'விவரங்களை காண்க',
    yourCraft: 'உங்கள் தயாரிப்பு',
    outOfStock: 'இருப்பில் இல்லை',
    inStock: 'இருப்பில் உள்ளது',
    craftPassport: '🧾 கைவினை பாஸ்போர்ட்',
    handmade: 'கையால் செய்யப்பட்டது',
    productionTime: 'தயாரிப்பு நேரம்',
    rawMaterials: 'மூலப்பொருட்கள்',
    craftDescription: 'தயாரிப்பு விவரம்',
    craftStory: 'பாரம்பரிய கதை',
    translateBtn: '🌐 AI மொழிபெயர்ப்பு',
    translating: 'மொழிபெயர்க்கிறது...',
    meetArtisan: 'கைவினைஞரை சந்திக்கவும்',
    viewProfile: 'சுயவிவரத்தை காண்க',
    saveToWishlist: 'விருப்பப்பட்டியலில் சேர்',
    home: 'முகப்பு',
    artisanStudio: 'கைவினைஞர் ஸ்டுடியோ',
    buyerMarketplace: 'நேரலை சந்தை',
    signIn: 'உள்நுழை',
    enterpriseTag: 'எண்டர்பிரைஸ்',
    offline: 'ஆஃப்லைன்',
    cloud: 'கிளவுட்',
    studio: 'ஸ்டுடியோ',
    market: 'சந்தை',
    filters: 'வடிப்பான்கள்',
    rankedByInterest: 'வாங்குபவர் ஆர்வத்தின் படி வரிசைப்படுத்தப்பட்டது',
    dashboard: 'டாஷ்போர்டு',
    myProducts: 'என் தயாரிப்புகள்',
    smartPricing: 'ஸ்மார்ட் விலை நிர்ணயம்',
    ordersAndFulfillment: 'ஆர்டர்கள் & டெலிவரி',
    marketIntelligence: 'சந்தை நுண்ணறிவு',
    salesChannels: 'விற்பனை சேனல்கள் (ONDC)',
    aiAssistantHeader: '🤖 கைவினைஞர் AI உதவி',
    askMeAnything: 'என்னிடம் எதையும் கேளுங்கள்...',
    generateAiDraftBtn: '🪄 AI வரைவை உருவாக்குங்கள்',
    nextBtn: 'அடுத்தது (Next)',
    backBtn: 'பின்செல் (Back)',
    recordVoiceStory: '🎙️ உங்கள் குரலில் கதையைப் பதிவுசெய்யவும்',
    ondcPlatformTag: 'இந்திய கைவினை டிஜிட்டல் தளம் • ONDC Ready Platform',
    heroHeadlineText: 'குரல் வழிகாட்டுதல் AI மற்றும் நியாயமான வர்த்தகத்துடன் இந்திய கைவினைஞர்களுக்கு அதிகாரம் அளித்தல்.',
    heroSubheadText: 'தடைசெய்கின்ற இடைத்தரகர்களை அகற்றி, பலமொழி குரல் AI, 20% பாதுகாக்கப்பட்ட லாப விலை மற்றும் நேரடி வாங்குபவர் இணைப்பு.',
    enterStudio: 'கைவினைஞர் ஸ்டுடியோ நுழைவு',
    artisanSignInJoin: 'கைவினைஞர் உள்நுழைவு / சேரவும்',
    exploreMarketplace: 'சந்தையை ஆராயுங்கள்',
    trustDirectArtisan: '100% நேரடியாக கைவினைஞருக்கு',
    trust5Languages: '5 இந்திய மொழிகள்',
    trustMarginGuard: '≥ 20% லாப பாதுகாப்பு',
    trustNoMiddlemen: 'இடைத்தரகர் கமிஷன் இல்லை',
    whyTrustTitle: 'கிராமப்புற கைவினைஞர்களும் வாங்குபவர்களும் ஏன் Artisan AI-ஐ நம்புகிறார்கள்',
    whyTrustSub: 'இந்திய கைவினைஞர்கள் ఎదుర్కొடும் சிக்கல்களை தீர்க்க உருவாக்கப்பட்டது.',
    preservingHeritageTag: 'பாரம்பரிய பாதுகாப்பு',
    giCraftsTitle: 'அங்கீகரிக்கப்பட்ட புவிசார் குறியீடு (GI) கைவினைப்பொருட்கள்',
    viewAllCraftsMarketplace: 'சந்தையில் உள்ள அனைத்து பொருட்களையும் காண்க',
    exploreInCatalog: 'பட்டியலில் ஆராயுங்கள்',
    howItWorksTitle: 'இது எவ்வாறு செயல்படுகிறது',
    howItWorksSub: 'கைவினைஞருக்கு எளிமையானது. வாங்குபவருக்கு வெளிப்படையானது.',
    forMasterArtisans: 'கைவினைஞர்களுக்காக',
    fromWorkshopToGlobal: 'பட்டறையிலிருந்து உலகளாவிய சந்தைக்கு',
    artisanStep1Text: 'பேசுங்கள் & படம் எடுங்கள்: உங்கள் தாய்மொழியில் பேசி படத்தை பதிவேற்றுங்கள்.',
    artisanStep2Text: 'உடனடி நியாயமான விலை: AI 20% குறைந்தபட்ச லாபத்துடன் நியாயமான விலையை கணக்கிடுகிறது.',
    artisanStep3Text: 'நேரடி தொடர்புகள்: கமிஷன் இல்லாமல் நேரடியாக வாட்ஸ்அப் தொடர்புகளை பெறுங்கள்.',
    forConsciousBuyers: 'வாங்குபவர்களுக்காக',
    directProvenance: 'நேரடியாக கைவினைஞரிடம் இருந்து',
    buyerStep1Text: 'பாரம்பரிய பொருட்களை தேடுங்கள்: GI குறிச்சொல் மற்றும் விவரங்களுடன் தேடுங்கள்.',
    buyerStep2Text: 'வெளிப்படையான விலை: மூலப்பொருட்கள் மற்றும் உழைப்பு செலவு விவரங்களை காணவும்.',
    buyerStep3Text: 'நேரடி ஆர்டர்: வாட்ஸ்அப் மூலம் நேரடியாக ஆர்டர் செய்யுங்கள்.',
    readyToExperience: 'கைவினைப்பொருட்கள் வணிகத்தில் இணைய தயாரா?',
    joinThousands: 'ஆயிரக்கணக்கான கைவினைஞர்களின் படைப்புகளை உங்கள் வீட்டிற்கு கொண்டு வாருங்கள்.',
    startAsArtisan: 'கைவினைஞராக தொடங்குங்கள்',
    shopHandmadeCrafts: 'கைவினைப்பொருட்களை வாங்குங்கள்',
    connectingBackend: 'Artisan AI சேவையகத்துடன் இணைக்கிறது...',
    homeShowcase: 'முகப்பு காட்சி',
    offlineLocalCache: 'ஆஃப்லைன் (உள்ளூர் சேமிப்பு)',
    liveCloudDb: 'லைவ் (கிளவுட் தரவுத்தளம்)',
    nativeOnboardingBadge: 'தாய்மொழி தேர்வு',
    selectLanguageModalTitle: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    selectLanguageModalSub: 'Artisan AI உங்கள் தாய்மொழியில் வழிகாட்டுதலை வழங்குகிறது.',
    workspaceLabel: 'வேலைப்பகுதி',
    syncLabel: 'ஒத்திசைவு',
    databaseLabel: 'தரவுத்தளம்',
    connectedStatus: 'இணைக்கப்பட்டது'
  },
  bn: {
    selectLanguageTitle: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    selectLanguageSub: 'Artisan AI আপনার মাতৃভাষায় নির্দেশিকা এবং তথ্য প্রদান করে।',
    continueBtn: 'এগিয়ে যান',
    navbarTitle: 'কারিগর AI মার্কেটপ্লেস',
    addProductBtn: '🎨 + কারুশিল্প যোগ করুন (AI Guide)',
    buyerCopilotBtn: '🤖 AI ক্রেতা গাইড',
    sellTab: 'কারিগর ড্যাশবোর্ড',
    buyTab: 'লাইভ মার্কেটপ্লেস',
    analyticsTab: 'বিক্রয় রিপোর্ট',
    heroTag: 'সুরক্ষিত ন্যূনতম মুনাফা এবং ডিজিটাল বাণিজ্য',
    minFairPriceLabel: '২০% সুরক্ষিত ন্যূনতম মুনাফা মূল্য',
    smartPricingLabel: 'স্বয়ংক্রিয় স্মার্ট প্রাইসিং',
    publishBtn: 'মার্কেটপ্লেসে লাইভ প্রকাশ করুন',
    editAiDraftBtn: 'এডিট করুন (Edit AI Draft)',
    photoStepTitle: '১. ছবি আপলোড করুন',
    photoStepSub: 'পণ্যর ছবি যোগ করুন এবং Next এ ক্লিক করুন',
    nameStepTitle: '২. পণ্যের নাম ও বিবরণ',
    costStepTitle: '৩. উপাদান ও শ্রম খরচ',
    storyStepTitle: '৪. কারুশিল্পের গল্প / ভয়েস মেসেজ',
    reviewStepTitle: '৫. AI ড্রাফট পর্যালোচনা ও ২০% সুরক্ষিত মূল্য',
    searchPlaceholder: 'কারুশিল্প অনুসন্ধান করুন...',
    allCrafts: 'সমস্ত কারুশিল্প',
    directFairPrice: 'ন্যায্য মূল্য',
    buyNow: 'এখনই কিনুন',
    preOrder: 'প্রাক-অর্ডার করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    yourCraft: 'আপনার পণ্য',
    outOfStock: 'স্টক নেই',
    inStock: 'স্টকে আছে',
    craftPassport: '🧾 ক্রাফট পাসপোর্ট',
    handmade: 'হাতে তৈরি',
    productionTime: 'তৈরির সময়',
    rawMaterials: 'কাঁচামাল',
    craftDescription: 'পণ্যের বিবরণ',
    craftStory: 'ঐতিহ্যের গল্প',
    translateBtn: '🌐 AI অনুবাদ',
    translating: 'অনুবাদ হচ্ছে...',
    meetArtisan: 'কারিগরের সাথে পরিচিত হন',
    viewProfile: 'প্রোফাইল দেখুন',
    saveToWishlist: 'উইশলিস্টে সংরক্ষণ করুন',
    home: 'হোম',
    artisanStudio: 'কারিগর স্টুڈیو',
    buyerMarketplace: 'লাইভ মার্কেটপ্লেস',
    signIn: 'সাইন ইন',
    enterpriseTag: 'এন্টারপ্রাইজ',
    offline: 'অফলাইন',
    cloud: 'ক্লাউড',
    studio: 'স্টুডিও',
    market: 'মার্কেট',
    filters: 'ফিল্টার',
    rankedByInterest: 'ক্রেতার আগ্রহ অনুযায়ী র্যাঙ্ক করা হয়েছে',
    dashboard: 'ড্যাশবোর্ড',
    myProducts: 'আমার পণ্যসমূহ',
    smartPricing: 'স্মার্ট প্রাইসিং ও মুনাফা',
    ordersAndFulfillment: 'অর্ডার এবং ডেলিভারি',
    marketIntelligence: 'মার্কেট ইন্টেলিজেন্স',
    salesChannels: 'বিক্রয় চ্যানেল (ONDC)',
    aiAssistantHeader: '🤖 কারিগর AI সহকারী',
    askMeAnything: 'আমাকে যেকোনো প্রশ্ন জিজ্ঞাসা করুন...',
    generateAiDraftBtn: '🪄 AI ড্রাফট তৈরি করুন',
    nextBtn: 'পরবর্তী ধাপ',
    backBtn: 'পিছনে যান',
    recordVoiceStory: '🎙️ আপনার নিজের গলায় গল্প বলুন',
    ondcPlatformTag: 'ভারতীয় ডিজিটাল হস্তশিল্প মঞ্চ • ONDC Ready Platform',
    heroHeadlineText: 'ভয়েস AI এবং ন্যায্য বাণিজ্যের মাধ্যমে ভারতীয় কারিগরদের ক্ষমতায়ন।',
    heroSubheadText: 'মধ্যস্বত্বভোগীদের অবসান ঘটিয়ে বহুভাষিক ভয়েস AI, ২০% সুরক্ষিত লাভ মূল্য এবং সরাসরি ক্রেতার সাথে সংযোগ।',
    enterStudio: 'কারিগর স্টুডিওতে প্রবেশ করুন',
    artisanSignInJoin: 'কারিগর সাইন ইন / যোগ দিন',
    exploreMarketplace: 'মার্কেটপ্লেস অন্বেষণ করুন',
    trustDirectArtisan: '১০০% সরাসরি কারিগরের কাছে',
    trust5Languages: '৫টি ভারতীয় ভাষা',
    trustMarginGuard: '≥ ২০% মুনাফা সুরক্ষা',
    trustNoMiddlemen: 'কোনো মধ্যস্বত্বভোগী কমিশন নেই',
    whyTrustTitle: 'কেন গ্রামীণ কারিগর ও ক্রেতারা Artisan AI-কে বিশ্বাস করেন',
    whyTrustSub: 'সমগ্র ভারতের কারিগরদের আসল সমস্যা সমাধানের জন্য তৈরি।',
    preservingHeritageTag: 'ঐতিহ্য সংরক্ষণ',
    giCraftsTitle: 'প্রামাণিক ভৌগোলিক নির্দেশক (GI) কারুশিল্প',
    viewAllCraftsMarketplace: 'মার্কেটপ্লেসে সব কারুশিল্প দেখুন',
    exploreInCatalog: 'ক্যাটালগে দেখুন',
    howItWorksTitle: 'এটি যেভাবে কাজ করে',
    howItWorksSub: 'কারিগরের জন্য সহজ পদ্ধতি। ক্রেতার জন্য বিশ্বাস ও স্বচ্ছতা।',
    forMasterArtisans: 'কারিগরদের জন্য',
    fromWorkshopToGlobal: 'ওয়ার্কশপ থেকে বিশ্ববাজারে',
    artisanStep1Text: 'কথা বলুন ও ছবি তুলুন: নিজের ভাষায় কথা বলুন এবং ছবি আপলোড করুন।',
    artisanStep2Text: 'তাত্ক্ষণিক ন্যায্য মূল্য: AI ২০% নিশ্চিত মুনাফাসহ মূল্য নির্ধারণ করে।',
    artisanStep3Text: 'সরাসরি ক্রেতা: কমিশন ছাড়াই সরাসরি হোয়াটসঅ্যাপ কল ও অর্ডার পান।',
    forConsciousBuyers: 'সচেতন ক্রেতাদের জন্য',
    directProvenance: 'সরাসরি কারিগরের থেকে',
    buyerStep1Text: 'প্রামাণিক শিল্প খুঁজুন: GI ট্যাগ এবং কারিগরের বিবরণ অনুযায়ী খুঁজুন।',
    buyerStep2Text: 'মূল্য স্বচ্ছতা: কাঁচামাল ও শ্রম খরচের বিস্তারিত দেখুন।',
    buyerStep3Text: 'সরাসরি অর্ডার করুন: হোয়াটসঅ্যাপের মাধ্যমে সরাসরি অর্ডার করুন।',
    readyToExperience: 'হস্তশিল্পের আন্তর্জাতিক বাজারে যোগ দিতে প্রস্তুত?',
    joinThousands: 'হাজার হাজার গ্রামীণ কারিগরের শিল্প আপনার বাড়িতে আনুন।',
    startAsArtisan: 'কারিগর হিসাবে শুরু করুন',
    shopHandmadeCrafts: 'হস্তশিল্প কিনুন',
    connectingBackend: 'Artisan AI সার্ভারের সাথে সংযুক্ত হচ্ছে...',
    homeShowcase: 'হোম শোকেস',
    offlineLocalCache: 'অফলাইন (লোকাল ক্যাশ)',
    liveCloudDb: 'লাইভ (ক্লাউড ডিবি)',
    nativeOnboardingBadge: 'মাতৃভাষা নির্বাচন',
    selectLanguageModalTitle: 'আপনার ভাষা নির্বাচন করুন',
    selectLanguageModalSub: 'Artisan AI আপনার মাতৃভাষায় নির্দেশিকা এবং পরিষেবা প্রদান করে।',
    workspaceLabel: 'ওয়ার্কস্পেস',
    syncLabel: 'সিঙ্ক',
    databaseLabel: 'ডাটাবেস',
    connectedStatus: 'সংযুক্ত'
  }
};

export function getLocalizedCategory(categoryName, lang = 'en') {
  if (!categoryName) return '';
  const item = CATEGORY_TRANSLATIONS[categoryName];
  if (item && item[lang]) {
    return item[lang];
  }
  return categoryName;
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('artisan_app_language') || 'te';
  });

  const [isSelectingLanguage, setIsSelectingLanguage] = useState(() => {
    return !localStorage.getItem('artisan_app_language');
  });

  const triggerGoogleTranslate = useCallback((langCode) => {
    try {
      const target = langCode || 'en';
      if (target === 'en') {
        document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
        document.cookie = `googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=${window.location.hostname}; path=/;`;
      } else {
        document.cookie = `googtrans=/en/${target}; path=/`;
        document.cookie = `googtrans=/en/${target}; domain=${window.location.hostname}; path=/`;
      }
    } catch (e) {
      console.warn('Google Translate cookie error:', e);
    }
  }, []);

  const setLanguage = (langCode) => {
    setLanguageState(langCode);
    localStorage.setItem('artisan_app_language', langCode);
    setIsSelectingLanguage(false);
    triggerGoogleTranslate(langCode);

    // Auto-reload window so Google Translate applies 100% full-page translation instantly
    window.location.reload();
  };

  useEffect(() => {
    if (language && language !== 'en') {
      triggerGoogleTranslate(language);
    }
  }, [language, triggerGoogleTranslate]);

  // Helper t(key, fallback) that retrieves translation for active language
  const t = (key, fallback = '') => {
    if (!key) return fallback || '';

    // 1. Check exact key in TRANSLATIONS[language]
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key]) {
      return langDict[key];
    }

    // 2. Check English dictionary if active is EN
    if (language === 'en') {
      const enDict = TRANSLATIONS.en;
      if (enDict && enDict[key]) {
        return enDict[key];
      }
    }

    // 3. Reverse search dictionary values to support passing English phrases
    for (const dict of Object.values(TRANSLATIONS)) {
      if (dict[key]) {
        const activeDict = TRANSLATIONS[language] || TRANSLATIONS.en;
        return activeDict[key] || fallback || key;
      }
    }

    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        isSelectingLanguage,
        setIsSelectingLanguage,
        t,
        getCategoryTranslation: (cat) => getLocalizedCategory(cat, language)
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

