"""add_token_version_and_processed_ops

Revision ID: 0359e10b53ec
Revises: 2d6563c27c30
Create Date: 2026-09-07 03:01:48.139210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0359e10b53ec'
down_revision: Union[str, Sequence[str], None] = '2d6563c27c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artisan_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('active_mode',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active_mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('token_version')

    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_column('replied_at')
        batch_op.drop_column('artisan_reply')

    # ### end Alembic commands ###
