"""create_initial_schema_numeric_money

Revision ID: 2d6563c27c30
Revises: 
Create Date: 2026-09-06 12:37:38.584293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6563c27c30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('active_mode', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('craft', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('craft_story', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('materials', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('enhanced_image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_margin_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('labour_cost >= 0', name='chk_product_lab_cost_non_negative'),
    sa.CheckConstraint('material_cost >= 0', name='chk_product_mat_cost_non_negative'),
    sa.CheckConstraint('packaging_cost >= 0', name='chk_product_pkg_cost_non_negative'),
    sa.CheckConstraint('price >= 0', name='chk_product_price_non_negative'),
    sa.CheckConstraint('stock >= 0', name='chk_product_stock_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_title'), ['title'], unique=False)

    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_phone', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metadata_info', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_phone', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_order_quantity_positive'),
    sa.CheckConstraint('total_price >= 0', name='chk_order_total_price_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='chk_order_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('pricing_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('previous_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('applied_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('demand_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('market_adjustment', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('reasoning_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint('applied_price >= 0', name='chk_pd_app_price_non_negative'),
    sa.CheckConstraint('previous_price >= 0', name='chk_pd_prev_price_non_negative'),
    sa.CheckConstraint('recommended_price >= 0', name='chk_pd_rec_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_decisions_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_decisions_product_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_decisions_id'))

    op.drop_table('pricing_decisions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))

    op.drop_table('orders')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_product_id'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_category'))

    op.drop_table('events')
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiries_user_id'))
        batch_op.drop_index(batch_op.f('ix_enquiries_product_id'))
        batch_op.drop_index(batch_op.f('ix_enquiries_id'))

    op.drop_table('enquiries')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_title'))
        batch_op.drop_index(batch_op.f('ix_products_seller_id'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
