"""remove_legacy_and_fix_sqlite

Revision ID: 7028678c0ed6
Revises: 0005_add_published_at
Create Date: 2026-09-21 11:30:06.242014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.database import is_sqlite

# revision identifiers, used by Alembic.
revision: str = '7028678c0ed6'
down_revision: Union[str, Sequence[str], None] = '0005_add_published_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    if is_sqlite:
        # SQLite doesn't support DROP DEFAULT or multiple ALTER COLUMN in one statement
        # We need to rely on the fact that these constraints are already enforced by the app or
        # use raw SQL for specific SQLite workarounds if absolutely necessary.
        # Since the app code previously handled this, we can potentially skip 
        # these specific ALTERs if they cause issues on SQLite.
        pass
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('draft_catalogs', 'is_consumed',
                   existing_type=sa.BOOLEAN(),
                   server_default=None,
                   existing_nullable=False)
        op.alter_column('orders', 'payment_method',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   existing_nullable=True)
        op.alter_column('orders', 'payment_status',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   nullable=False)
        op.alter_column('orders', 'status',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        op.alter_column('orders', 'cancellation_status',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   nullable=False)
        op.alter_column('payments', 'currency',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   existing_nullable=False)
        op.alter_column('payments', 'status',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   existing_nullable=False)
        op.alter_column('payments', 'signature_verified',
                   existing_type=sa.BOOLEAN(),
                   server_default=None,
                   existing_nullable=False)
        op.alter_column('products', 'handmade_pct',
                   existing_type=sa.INTEGER(),
                   server_default=None,
                   nullable=False)
        op.alter_column('products', 'production_time_days',
                   existing_type=sa.INTEGER(),
                   server_default=None,
                   existing_nullable=True)
        op.alter_column('products', 'verification_status',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   nullable=False)
        op.alter_column('products', 'status',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        op.alter_column('products', 'other_cost',
                   existing_type=sa.NUMERIC(precision=12, scale=2),
                   server_default=None,
                   nullable=False)
        op.alter_column('products', 'auto_smart_pricing_enabled',
                   existing_type=sa.BOOLEAN(),
                   server_default=None,
                   nullable=False)
        op.create_unique_constraint('uq_review_order_product_buyer', 'reviews', ['order_id', 'product_id', 'buyer_id'])
        op.alter_column('users', 'status',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   nullable=False)
        op.alter_column('users', 'active_mode',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   existing_nullable=True)
        op.alter_column('users', 'avatar_url',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('users', 'experience_years',
                   existing_type=sa.INTEGER(),
                   server_default=None,
                   nullable=False)
        op.alter_column('users', 'verification_status',
                   existing_type=sa.VARCHAR(),
                   server_default=None,
                   nullable=False)
        op.create_index(op.f('ix_users_push_token'), 'users', ['push_token'], unique=False)
        # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    if is_sqlite:
        pass
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index(op.f('ix_users_push_token'), table_name='users')
        op.alter_column('users', 'verification_status',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'UNVERIFIED'"),
                   nullable=True)
        op.alter_column('users', 'experience_years',
                   existing_type=sa.INTEGER(),
                   server_default=sa.text('0'),
                   nullable=True)
        op.alter_column('users', 'avatar_url',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        op.alter_column('users', 'active_mode',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'BUYER'"),
                   existing_nullable=True)
        op.alter_column('users', 'status',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'ACTIVE'"),
                   nullable=True)
        op.drop_constraint('uq_review_order_product_buyer', 'reviews', type_='unique')
        op.alter_column('products', 'auto_smart_pricing_enabled',
                   existing_type=sa.BOOLEAN(),
                   server_default=sa.text('0'),
                   nullable=True)
        op.alter_column('products', 'other_cost',
                   existing_type=sa.NUMERIC(precision=12, scale=2),
                   server_default=sa.text('(0.00)'),
                   nullable=True)
        op.alter_column('products', 'status',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        op.alter_column('products', 'verification_status',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'UNVERIFIED'"),
                   nullable=True)
        op.alter_column('products', 'production_time_days',
                   existing_type=sa.INTEGER(),
                   server_default=sa.text('3'),
                   existing_nullable=True)
        op.alter_column('products', 'handmade_pct',
                   existing_type=sa.INTEGER(),
                   server_default=sa.text('(100)'),
                   nullable=True)
        op.alter_column('payments', 'signature_verified',
                   existing_type=sa.BOOLEAN(),
                   server_default=sa.text("'0'"),
                   existing_nullable=False)
        op.alter_column('payments', 'status',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'CREATED'"),
                   existing_nullable=False)
        op.alter_column('payments', 'currency',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'INR'"),
                   existing_nullable=False)
        op.alter_column('orders', 'cancellation_status',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'NONE'"),
                   nullable=True)
        op.alter_column('orders', 'status',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        op.alter_column('orders', 'payment_status',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'UNPAID'"),
                   nullable=True)
        op.alter_column('orders', 'payment_method',
                   existing_type=sa.VARCHAR(),
                   server_default=sa.text("'UPI'"),
                   existing_nullable=True)
        op.alter_column('draft_catalogs', 'is_consumed',
                   existing_type=sa.BOOLEAN(),
                   server_default=sa.text('0'),
                   existing_nullable=False)
        # ### end Alembic commands ###

