from decimal import Decimal
from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from backend.app.database import get_db
from backend.app.models import Product, User
from backend.app.schemas import ProductResponse
from backend.app.services.ai_adapter import generate_catalog_draft
from backend.app.services.auth import get_current_user

router = APIRouter(prefix="/api/ai", tags=["AI Cataloging"])

class AICatalogRequest(BaseModel):
    voice_description: str = Field(..., min_length=2, max_length=5000, description="Artisan voice note or text description")
    language: str = Field("en", max_length=10, description="Language code e.g. en, te, hi")
    image_url: Optional[str] = Field(None, max_length=2000, description="User-provided photo URL")
    category_hint: Optional[str] = Field(None, max_length=100, description="Optional craft category hint")
    material_cost: Optional[float] = Field(None, ge=0, description="Artisan actual material expense in INR")
    labour_cost: Optional[float] = Field(None, ge=0, description="Artisan actual labour value in INR")
    packaging_cost: Optional[float] = Field(None, ge=0, description="Artisan actual packaging cost in INR")

class AICatalogDraftResponse(BaseModel):
    source: str = Field(..., description="Draft origin: LIVE_AI, MANUAL_DRAFT, or DEMO_FALLBACK")
    is_live_ai: bool = Field(True, description="True if generated by live upstream AI provider")
    is_demo_data: bool = Field(False, description="True if generated using isolated demo sample data")
    requires_artisan_verification: bool = Field(True, description="Safety rule: AI outputs require human artisan verification")
    title: str
    category: str
    materials: str
    description: str
    craft_story: str
    tags: List[str] = Field(default_factory=list)
    suggested_price: Optional[Decimal] = None
    min_fair_price: Optional[Decimal] = None
    material_cost: Optional[Decimal] = None
    labour_cost: Optional[Decimal] = None
    packaging_cost: Optional[Decimal] = None
    min_margin_pct: Decimal = Decimal("0.20")
    pricing_available: bool = True
    pricing_source: str = "COST_BASED_CALCULATION"
    image_url: str = ""
    enhanced_image_url: str = ""
    transcription: str = ""
    language_detected: str = "en"
    lifecycle_state: str = "AI_GENERATED"
    notice: Optional[str] = None

class CatalogApproveRequest(BaseModel):
    title: str = Field(..., min_length=2, max_length=255)
    category: str = Field(..., min_length=2, max_length=100)
    materials: Optional[str] = Field(None, max_length=500)
    description: Optional[str] = None
    craft_story: Optional[str] = None
    price: Decimal = Field(..., ge=0)
    stock: int = Field(5, ge=0)
    material_cost: Optional[Decimal] = Field(None, ge=0)
    labour_cost: Optional[Decimal] = Field(None, ge=0)
    packaging_cost: Optional[Decimal] = Field(None, ge=0)
    min_margin_pct: Decimal = Field(Decimal("0.20"), ge=0)
    image_url: Optional[str] = None
    enhanced_image_url: Optional[str] = None
    status: str = "PUBLISHED"

@router.post("/process-catalog", response_model=AICatalogDraftResponse)
async def process_voice_and_image(req: AICatalogRequest):
    draft = await generate_catalog_draft(
        voice_description=req.voice_description,
        language=req.language,
        image_url=req.image_url,
        category_hint=req.category_hint,
        material_cost=req.material_cost,
        labour_cost=req.labour_cost,
        packaging_cost=req.packaging_cost
    )
    return AICatalogDraftResponse(**draft)

@router.post("/approve-and-publish", response_model=ProductResponse, status_code=status.HTTP_201_CREATED)
def approve_and_publish_product(
    req: CatalogApproveRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    product = Product(
        title=req.title,
        category=req.category,
        materials=req.materials,
        description=req.description,
        craft_story=req.craft_story,
        price=req.price.quantize(Decimal("0.01")),
        stock=req.stock,
        material_cost=req.material_cost.quantize(Decimal("0.01")) if req.material_cost is not None else Decimal("0.00"),
        labour_cost=req.labour_cost.quantize(Decimal("0.01")) if req.labour_cost is not None else Decimal("0.00"),
        packaging_cost=req.packaging_cost.quantize(Decimal("0.01")) if req.packaging_cost is not None else Decimal("0.00"),
        min_margin_pct=req.min_margin_pct.quantize(Decimal("0.0001")),
        image_url=req.image_url,
        enhanced_image_url=req.enhanced_image_url,
        status=req.status,
        seller_id=current_user.id
    )
    db.add(product)
    db.commit()
    return product